### ISSUE TITLE
'Specified key was too long; max key length is 767 bytes' when running migrations on MySQL database

### ISSUE THREAD

**Issue by azaghal** [maykinmedia/django-regex-redirects#12]
When running migrations with `django-regex-redirects-0.0.6` while using a MariaDB database, an exception is thrown (snipped most parts of exception):

```
Running migrations:
  Applying regex_redirects.0003_auto_20170126_1823...Traceback (most recent call last):
...
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
```

This happens due to addition of `unique_together=set([('old_path', 'new_path', 'fallback_redirect')]),`.

Doing some searching, turns out it's a limitation of MariaDB/MySQL. Depending on the engine used  and settings, the maximum key length for an index ranges from 767 (InnoDB default), through 1000 (MyISAM), up to 3072 (InnoDB with barracuda and some extra settings). Not sure if this can be exceeded in any way.

My understanding of the whole thing might be a bit naive, but... I guess the reason the values will get exceeded (even with 3072 limit) is that the unique index is created on top of old_path (max length 2000) and new_path (max length), which easily exceeds the limit.

To add salt to the injure, SQLite works just fine :)

**Comment by alextreme** [comment]
I've only been using SQLite and Postgres so thanks for looking into this, I wasn't aware MySQL/Maria was this limited when it comes to indexes.

The solution would be to drop the unique together, remove migration 0003 and the db_index on old_path (as this field on its own would exceed the limit). Dropping the indexes might make more sense as the way the regex matching is done doesn't make use of the index anyway.

Feel free to make the required changes and submit a PR, and I'll do a new release to pypi.

**Comment by azaghal** [comment]
Thanks for quick feedback, I'll look into the pull request :)

**Comment by alextreme** [comment]
Thanks for the PR, I've uploaded 0.0.7 to PyPi so I'll assume this is now resolved.

**Comment by woutdp** [comment]
I'm having the same issue with a MariaDB database. I'm using version 0.2.0. with Django 2.1
I've tried it locally and reducing the `max_length` of the `old_path` and `new_path` to 255 fixes it.

Just making a new migration for it won't fix it though since migration https://github.com/maykinmedia/django-regex-redirects/blob/master/regex_redirects/migrations/0002_auto_20151217_1938.py triggers the error.

If you want I can make a PR that fixes it, but resets the migrations back to only the initial one.

**Comment by azaghal** [comment]
Not sure that is the same issue? The original problem I faced was realted to `unique_together` constraint that introduced an index MariaDB/MySQL couldn't handle. The 2000-varchar works perfectly fine for me with MariaDB on Debian Jessie, for example. Perhaps create a new issue with complete reproduction steps?
