### ISSUE TITLE
Tags for released versions

### ISSUE THREAD

**Issue by azaghal** [maykinmedia/django-regex-redirects#18]
Following-up on the small patch I submitted (thanks for already releasing an updated version! :), I was wondering if it would be possible to tag all of the releases in the git repo?

The main advantage from my perspective is being able to clone the repo and quickly switch back-and-forth between working and non-working commits.

**Comment by alextreme** [comment]
Sure, here you go: https://github.com/maykinmedia/django-regex-redirects/tree/v0.3.0

**Comment by azaghal** [comment]
A bit delayed from me, but - many thanks once again :)
