### ISSUE TITLE
Push new version to pypi

### ISSUE THREAD

**Issue by vontangen** [maykinmedia/django-regex-redirects#5]
Hi,

Could you please push a new version to pypi? The stale reference to get_current_site in the latest pypi release (v0.0.2), is preventing this plugin from working with Django 1.9

Thanks for a very useful plugin!

Jorgen

**Comment by alextreme** [comment]
I've uploaded 0.0.3 and verified that it's available via pypi, it seems PyPi didn't register 0.0.2 properly

**Comment by vontangen** [comment]
Thank you very much for handling this so quickly!

Jorgen

**Comment by alextreme** [comment]
No problem, glad you find this project useful!

**Comment by vontangen** [comment]
It definitely is! Light-weight and plenty powerful.

For MySQL v5.5.47 backend I get the following migration error related to changes introduced in 0002_auto_20151217_1938.py:

SystemCheckError: System check identified some issues:

ERRORS:
regex_redirects.Redirect.old_path: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.

**Comment by alextreme** [comment]
I'm not using this project with MySQL (might be a good reason to hook up Travis, even though this project is rather trivial).

I've just committed a change that drops the unique constraint. Could you give it a try? After you've confirmed it's working I'll upload a fixed version to PyPi.

**Comment by vontangen** [comment]
Works great with latest commit on master.
I just did a clean install and both migrations run without any complaints.

Thanks again for fixing this so quickly!

Jorgen

On Tue, Apr 19, 2016 at 1:22 PM, Alex de Landgraaf <notifications@github.com

**Comment by vontangen** [comment]
Thanks. 0.0.4 installs and works great!

Jorgen
