### ISSUE TITLE
Absolute URLs are handled as relative

### ISSUE THREAD

**Issue by azaghal** [maykinmedia/django-regex-redirects#7]
At the moment it seems that the middleware code will not handle absolute URLs (that include 'http/https' in front) correctly. The middleware will treat all replacement URLs as relative to the current host.

I had a quick look at the code, and then at some of the forks of your repo, and I noticed the issue seems to have been fixed [in a commit from vontangen/django-regex-redirects repo](https://github.com/vontangen/django-regex-redirects/commit/817495ead089036a2d07221fea1edf00d0ad986e). The fix looks quite trivial (just an if/else).

Environment:

- Django 1.10.4
- django-regex-redirects 0.0.4

Reproduction steps:

1. Set-up `django-regex-redirects` on top of existing Django project (as described in installation instructions).

2. Create a new redirect via Admin gui:

- Set `Redirect from` to `/absoluteredirect/`.
- Set `Redirect to` to `https://www.google.com/`.

3. Try visiting URL `/absoluteredirect/` via browser.

Expected results:

1. User is redirected to `https://www.google.com/`.

Actual results:

1. User receives `Server not found` error, with URL being `HOSThttps://www.google.com/` (where HOST is the FQDN/hostname used to access Django installation).

**Comment by alextreme** [comment]
Great, thanks for investigating this. I've merged the fork indicated and deployed to PyPI

**Comment by azaghal** [comment]
Thanks for putting out a new release so quickly, saved me from hard-coding some paths in Nginx :)
