### ISSUE TITLE
Duplicates: Bug or feature?

### ISSUE THREAD

**Issue by julesallen** [maykinmedia/django-regex-redirects#9]
Thanks for creating this! 

I'm able to create duplicates in the admin:

![image](https://cloud.githubusercontent.com/assets/871038/22120137/5f091f56-de4c-11e6-96e7-7ef14577fb79.png)

Is this on purpose?

**Comment by alextreme** [comment]
You're welcome!

No, that's not on purpose. Not much harm either way in my eyes, but a unique_together on the charfields+booleanfields would be neater.

**Comment by julesallen** [comment]
I know redirects are a power user feature but I'd suggest mimicking the contrib redirects might be easier for end users. I have one site with 2k redirects and it's already become a problem — one was deleted and the duplicate is still in there. Would you consider this a request to put a fix in? Thanks!

**Comment by alextreme** [comment]
I've added the unique_together and uploaded a new version to pypi.

The only issue with adding a unique_together is that you'll run into your duplicates when adding the constraint via the migration, you'll have to do a datamigration beforehand to ensure duplicates have been removed.

**Comment by julesallen** [comment]
Fantastic, thank you so much.
